FROM imriss/megaman_archlinux:compact

RUN echo 'megaman: Manifold Learning for Millions of Points on Arch Linux'

MAINTAINER Reza Farrahi <imriss@ieee.org>
LABEL description="megaman: Manifold Learning for Millions of Points on Arch Linux"
